machines:
  - id: demo
    enabled: !!bool true
    type: l99.driver.opcxmlda.OpcxmldaMachine, opcxmlda
    strategy_type: l99.driver.opcxmlda.collectors.Basic01, opcxmlda
    handler_type: l99.driver.opcxmlda.handlers.SHDR, opcxmlda
    sweep_ms: !!int 1000
    net_uri: http://opcxml.demo-this.com/XmlDaSampleServer/Service.asmx
    net_timeout_s: !!int 3
    shdr_port: !!int 7878
    shdr_verbose: !!bool true
    data:
      - Dynamic/Analog Types/Double:
          shdr:
            name: analog_double
            category: sample
      - Dynamic/Analog Types/Int:
          shdr:
            name: analog_int
            category: sample
      - Dynamic/Analog Types/Double[]:
      - Static/Simple Types/String:
          shdr:
            name: simple_string
            category: event
      - Static/Simple Types/DateTime:
          shdr:
            name: simple_datetime
            category: event
      - Static/ArrayTypes/Object[]:
      - Dynamic/Analog Types/Fools/Guildenstern:
      - Dynamic/Enumerated Types/Gems:
      - SomeUnknownItem:
    broker:
      enabled: !!bool true
      net_ip: 10.20.30.102
      net_port: !!int 1883
      auto_connect: !!bool true
      publish_status: !!bool true
      publish_arrivals: !!bool true
      publish_changes: !!bool true
      publish_disco: !!bool true
      disco_base_topic: opcxmlda
    l99.driver.opcxmlda.handlers.SHDR, opcxmlda:
      port: !!int 7878
      verbose: !!bool true
    
  